#' Creates a blank plot with the specified limits
#'
#' @param xlim,ylim Numeric vectors of length 2, giving the x and y coordinates ranges.
#' @export
new_plot <- function(xlim,ylim, asp=NA) {
  plot.new()
  plot.window(xlim=xlim,ylim=ylim,xaxs='i',yaxs='i', asp=asp)
}

#' Makes a new plot with pretty axes
#'
#' Makes a new plot with \code{\link{new_plot}} and a bounding box and axes using \code{\link{pretty_axes}}
#' @inheritDotParams pretty_axes
#' @export
pretty_plot <- function(xlim,ylim, y2lim=NA,...) {
  new_plot(xlim,ylim)
  if(xlim[[2]]<xlim[[1]]) xlim=rev(xlim)
  if(ylim[[2]]<ylim[[1]]) ylim=rev(ylim)
  pretty_axes(xlim=xlim,ylim=ylim, y2lim=y2lim,...)
}


#' Calculates a tick inteval to make pretty plots
#' @param range The axis range
#' @param frac Allow fractional intervals?
#' @export
tick_interval <- function(range,frac=FALSE) {
  if(length(range) != 1) stop("'range' must be of length 1")
  nice=c(1,2,5,10)
  ti=10^floor(log10(range)) * nice[[which(range <= 10^floor(log10(range)) * nice)[[1]]]]/10
  if(!frac) {
    ti=ceiling(ti)
  }
  ti
}

#' Calculates tick locations to make pretty plots
#' @param min,max The minimum / maximum axis limits
#' @param div Divide the calculated interval by this number (to generate minor ticks)
#' @param frac Allow fractional intervals?
#' @param flexible Allow min and max to be adjusted for prettier results?
#' @export
pretty_ticks <- function(min,max,frac=FALSE, div=1, flexible=TRUE, forcedInterval=NA) {
  if(is.na(forcedInterval))
    tickInterval<-tick_interval(max-min,frac=frac)/div
  else
    tickInterval<-forcedInterval/div
  tickStart=signif(min,1)
  tickEnd=signif(max,1)
  #Range is only to 1 sf, so extend it to make sure we cover everything
  ticksat=seq(tickStart-tickInterval*10,tickEnd+tickInterval*10,tickInterval)
  if(flexible) {
    ticksat=round(ticksat/tickInterval)*tickInterval
  }
  ticksat
}


#' Draws a bounding box and pretty axes
#'
#' Draws a bounding box and axes with tick positions generated by \code{\link{pretty_ticks}}
#' @param xlim,ylim,y2lim Numeric vectors of length 2, giving the x, y (and y2) coordinate ranges.
#' @param xlab,ylab,y2lab Titles for the x,y,y2 axes
#' @param axes Which axes to draw c(1,2,3,4) -- 1 & 3 == x; 2=y; 4=y2
#' @param div Factor by which the minor tick interval is smaller than the major tick interval c(x,y,y2)
#' @param labline Which margin line to draw the labels on c(x,x2,y,y2)
#' @param ... Additional parameters are passed to the underlying function calls
#' @inheritParams pretty_ticks
#' @export
pretty_axes <- function(xlim=c(0,1),ylim=c(0,1), y2lim=NA, axes=c(1,2),
                        drawBox=TRUE,frac=FALSE,div=1,flexible=TRUE,xlab=NULL,
                        ylab=NULL,y2lab=NULL,line = -0.6, labline=NULL, invertX=FALSE, lowerTickLimit=c(NA,NA,NA), lowerLabelLimit=c(NA,NA,NA), upperTickLimit=c(NA,NA,NA), upperLabelLimit=c(NA,NA,NA), forcedInterval=NA, forcePrint=FALSE, ...) {
  #Draw the bounding box
  if(drawBox) box()
  forcePrint_=force(forcePrint)
  draw_axis <- function(min, max,
                        axisSide,
                        frac, div, flexible,
                        line=line,
                        scale=c(1,0),
                        invert=F,
                        lowerTickLimit=NA, lowerLabelLimit=NA,
                        upperTickLimit=NA, upperLabelLimit=NA,
                        forcedInterval=NA,
                        forcePrint=forcePrint_, ...) {
    #Add some axes
    ticksat=pretty_ticks(min,max,frac,div=1,flexible,forcedInterval)
    Minorticksat=pretty_ticks(min,max,frac,div,flexible)
    Minorticksat=Minorticksat[!(Minorticksat %in% ticksat)]

    if(!is.na(upperTickLimit)) {
      m = if(invert) -1 else 1
      ticksat=ticksat[m*ticksat<=upperTickLimit]
      Minorticksat=Minorticksat[m*Minorticksat<=upperTickLimit]
    }
    if(!is.na(lowerTickLimit)) {
      m = if(invert) -1 else 1
      ticksat=ticksat[m*ticksat>=lowerTickLimit]
      Minorticksat=Minorticksat[m*Minorticksat>=lowerTickLimit]
    }

    #Add minor ticks
    axis(side = axisSide, tcl = -.2, at=Minorticksat*scale[[1]]+scale[[2]], labels = NA,...)
    #Add major ticks
    axis(side = axisSide, tcl = -.4, at=ticksat*scale[[1]]+scale[[2]], labels = NA,...)

    if(!is.na(upperLabelLimit)) {
      m = if(invert) -1 else 1
      ticksat=ticksat[m*ticksat<=upperLabelLimit]
      Minorticksat=Minorticksat[m*Minorticksat<=upperLabelLimit]
    }
    if(!is.na(lowerLabelLimit)) {
      m = if(invert) -1 else 1
      ticksat=ticksat[m*ticksat>=lowerLabelLimit]
      Minorticksat=Minorticksat[m*Minorticksat>=lowerLabelLimit]
    }

    #Add labels (With reduced spacing from axis -- line=.4)
    mult = if(invert) -1 else 1
    if(forcePrint) {
      ta1=ticksat[c(T,F)]
      ta2=ticksat[c(F,T)]
      axis(side = axisSide, lwd = 0,tcl = -0.5, line = line, at=ta1*scale[[1]]+scale[[2]],labels=ta1*mult,...)
      axis(side = axisSide, lwd = 0,tcl = -0.5, line = line, at=ta2*scale[[1]]+scale[[2]],labels=ta2*mult,...)
    } else
      axis(side = axisSide, lwd = 0,tcl = -0.5, line = line, at=ticksat*scale[[1]]+scale[[2]],labels=ticksat*mult,...)
  }
  if(length(div)==1) div=c(div,div,div)
  if(length(div)==2) div=c(div[[1]],div[[2]],div[[2]])

  if(is.null(labline)) {
    labline=c(1.7,1.3,1.6,1.6)
    labline[!c(1,2,3,4)%in%axes]=labline[!c(1,2,3,4)%in%axes]-1.2
  }

  if(length(labline)==1) labline=c(labline,labline,labline,labline)
  if(length(labline)==2) labline=c(labline[[1]],labline[[2]],labline[[1]],labline[[2]])
  if(length(labline)==3) labline=c(labline[[1]],labline[[2]],labline[[1]],labline[[3]])

  if(length(line)==1) line=c(line,line,line,line)
  if(length(line)==2) line=c(line[[1]],line[[2]],line[[1]],line[[2]])
  if(length(line)==3) line=c(line[[1]],line[[2]],line[[1]],line[[3]])

  if(length(forcedInterval)==1) forcedInterval=c(forcedInterval,NA,NA)
  if(length(forcedInterval)==2) forcedInterval=c(forcedInterval[1:2],NA)

  if(1%in%axes) {
    #Draw x axis
    draw_axis(xlim[[1]],xlim[[2]],1,frac,div[[1]],flexible, invert=invertX, lowerTickLimit=lowerTickLimit[[1]], lowerLabelLimit=lowerLabelLimit[[1]], upperTickLimit=upperTickLimit[[1]], upperLabelLimit=upperLabelLimit[[1]], line=line[[1]],forcedInterval=forcedInterval[[1]], ...)
  }
  if(!is.null(xlab)) mtext(side = 1, as.expression(xlab), line = labline[[1]],...)
  if(3%in%axes) {
    #Draw x axis
    draw_axis(xlim[[1]],xlim[[2]],3,frac,div[[1]],flexible, invert=invertX, lowerTickLimit=lowerTickLimit[[1]], lowerLabelLimit=lowerLabelLimit[[1]], upperTickLimit=upperTickLimit[[1]], upperLabelLimit=upperLabelLimit[[1]], line=line[[3]],forcedInterval=forcedInterval[[1]], ...)
    if(!is.null(xlab)) mtext(side = 3, as.expression(xlab), line = labline[[3]], ...)
  }
  if(2%in%axes) {
    #Draw y axis
    draw_axis(ylim[[1]],ylim[[2]],2,frac,div[[2]],flexible,las=1, lowerTickLimit=lowerTickLimit[[2]], lowerLabelLimit=lowerLabelLimit[[2]], upperTickLimit=upperTickLimit[[2]], upperLabelLimit=upperLabelLimit[[2]],line=line[[2]],forcedInterval=forcedInterval[[2]],...)
  }
  if(!is.null(ylab)) mtext(side = 2, as.expression(ylab), line = labline[[2]], ...)
  if(!is.null(y2lim) && !any(is.na(y2lim))) plot_options$y2scale <- yscale(ylim,y2lim)
  if(4%in%axes) {
    #Draw x axis
    draw_axis(y2lim[[1]],y2lim[[2]],4,frac,div[[3]],flexible,scale=plot_options$y2scale,las=1, lowerTickLimit=lowerTickLimit[[3]], lowerLabelLimit=lowerLabelLimit[[3]], upperTickLimit=upperTickLimit[[3]], upperLabelLimit=upperLabelLimit[[3]],line=line[[4]],forcedInterval=forcedInterval[[3]], ...)
  }
  if(!is.null(y2lab)) mtext(side = 4, as.expression(y2lab), line = labline[[4]],...)
}

#' Calculate a scale factor to transform between vectors
#'
#' @param y1,y2 Numeric vectors
#' @return c(scale,offset) to transform y2 into the same range as y1
#' @export
yscale <- function(y1,y2) {
  ylim=range(y1)
  y2lim=range(y2)
  scale=(ylim[[2]]-ylim[[1]])/(y2lim[[2]]-y2lim[[1]])
  offset=ylim[[1]]-y2lim[[1]]*scale
  return(c(scale=scale,offset=offset))
}

#Prepare environment to store scale settings for y2 axis
plot_options=new.env()

