#' Creates a blank plot with the specified limits
#'
#' @param xlim,ylim Numeric vectors of length 2, giving the x and y coordinates ranges.
#' @export
new_plot <- function(xlim,ylim, asp=NA) {
  plot.new()
  plot.window(xlim=xlim,ylim=ylim,xaxs='i',yaxs='i', asp=asp)
}

#' Makes a new plot with pretty axes
#'
#' Makes a new plot with \code{\link{new_plot}} and a bounding box and axes using \code{\link{pretty_axes}}
#' @inheritDotParams pretty_axes
#' @export
pretty_plot <- function(xlim,ylim, y2lim=NA,...) {
  new_plot(xlim,ylim)
  if(xlim[[2]]<xlim[[1]]) xlim=rev(xlim)
  if(ylim[[2]]<ylim[[1]]) ylim=rev(ylim)
  pretty_axes(xlim=xlim,ylim=ylim, y2lim=y2lim,...)
}


#' Calculates a tick inteval to make pretty plots
#' @param range The axis range
#' @param frac Allow fractional intervals?
#' @export
tick_interval <- function(range,frac=FALSE) {
  if(length(range) != 1) stop("'range' must be of length 1")
  range <- abs(range)
  nice=c(1,2,5,10)
  ti=10^floor(log10(range)) * nice[[which(range <= 10^floor(log10(range)) * nice)[[1]]]]/10
  if(!frac) {
    ti=ceiling(ti)
  }
  ti
}

#' Calculates tick locations to make pretty plots
#' @param min,max The minimum / maximum axis limits
#' @param div Divide the calculated interval by this number (to generate minor ticks)
#' @param frac Allow fractional intervals?
#' @param flexible Allow min and max to be adjusted for prettier results?
#' @export
pretty_ticks <- function(min,max,frac=FALSE, div=1, flexible=TRUE, forcedInterval=NA) {
  if(min == max || !is.finite(min) || !is.finite(max)) return()

  if(min > max) {
    temp <- min
    min <- max
    max <- temp
  }

  if(is.na(forcedInterval))
    tickInterval<-tick_interval(max-min,frac=frac)/div
  else
    tickInterval<-forcedInterval/div


  if(flexible) {
    min = floor(min / tickInterval) * tickInterval
    max = ceiling(max / tickInterval) * tickInterval
  }

  seq(min,max,tickInterval)
}


expand_plot_args <- function(x) {
  if(length(x)==1) x=c(x, x, x, x)
  if(length(x)==2) x=c(x[[1]], x[[2]], x[[1]], x[[2]])
  if(length(x)==3) x=c(x[[1]], x[[2]], x[[1]], x[[3]])
  x
}

#' Draws a bounding box and pretty axes
#'
#' Draws a bounding box and axes with tick positions generated by \code{\link{pretty_ticks}}
#' @param xlim,ylim,y2lim Numeric vectors of length 2, giving the x, y (and y2) coordinate ranges.
#' @param xlab,ylab,y2lab Titles for the x,y,y2 axes
#' @param axes Which axes to draw c(1,2,3,4) -- 1 & 3 == x; 2=y; 4=y2
#' @param div Factor by which the minor tick interval is smaller than the major tick interval c(x,y,y2)
#' @param labline Which margin line to draw the labels on c(x,x2,y,y2)
#' @param lowerTickLimit,upperTickLimit Limits beyond which not to draw ticks
#' @param lowerLabelLimit,upperLabelLimit Limits beyond which not to draw labels
#' @param forcedInterval Override the calculated tick interval
#' @param forcePrint Attempt to print all labels even if they are closely spaced
#' @param ticklabels Print labels?
#' @param ticksOut Ticks point outwards?
#' @param centreTitlesToLabels Centre the axis title relative to the labels rather than the axis?
#' @param ... Additional parameters are passed to the underlying function calls
#' @inheritParams pretty_ticks
#' @export
pretty_axes <- function(xlim=c(0,1), ylim=c(0,1), y2lim=NA, axes=c(1,2),
                        drawBox=TRUE, frac=FALSE, div=1, flexible=TRUE, xlab=NULL,
                        ylab=NULL, y2lab=NULL,line = -0.6, labline=NULL,
                        lowerTickLimit=c(NA,NA,NA), lowerLabelLimit=c(NA,NA,NA),
                        upperTickLimit=c(NA,NA,NA), upperLabelLimit=c(NA,NA,NA),
                        forcedInterval=NA, forcePrint=FALSE, ticklabels=c(T,T,T),
                        cex=par('cex'), ticksOut=c(T,T,T), centreTitlesToLabels=c(F,F,F), ...) {
  #Draw the bounding box
  if(drawBox) box()

  if(is.null(labline)) {
    labline=c(1.7,1.3,1.6,1.6)
    labline[!c(1,2,3,4)%in%axes]=labline[!c(1,2,3,4)%in%axes]-1.2
  }

  div = expand_plot_args(div)
  frac = expand_plot_args(frac)
  forcedInterval = expand_plot_args(forcedInterval)
  labline = expand_plot_args(labline)
  line = expand_plot_args(line)
  ticklabels = expand_plot_args(ticklabels)
  ticksOut = expand_plot_args(ticksOut)
  centreTitlesToLabels = expand_plot_args(centreTitlesToLabels)
  lowerTickLimit = expand_plot_args(lowerTickLimit)
  upperTickLimit = expand_plot_args(upperTickLimit)
  lowerLabelLimit = expand_plot_args(lowerLabelLimit)
  upperLabelLimit = expand_plot_args(upperLabelLimit)
  cex = expand_plot_args(cex)
  flexible = expand_plot_args(flexible)
  forcePrint = expand_plot_args(forcePrint)

  if(!is.null(y2lim) && !any(is.na(y2lim))) plot_options$y2scale <- rescale(ylim,y2lim)

  for(a in axes) {
    scale = c(1,0)
    if(a %in% c(1,3)) {
      lim = xlim
      lab = xlab
      las=0
    } else if(a == 2) {
      lim = ylim
      lab = ylab
      las=1
    } else if(a ==4) {
      lim = y2lim
      lab = y2lab
      las=1
      scale=plot_options$y2scale
    } else {
      stop('Unknown axis ', a)
    }

    draw_axis(lim[[1]], lim[[2]], a, frac[[a]], div[[a]], flexible[[a]], scale=scale, las=las,
              lab=lab, labline=labline[[a]], labcex=cex[[a]], centreTitlesToLabels=centreTitlesToLabels[[a]],
              lowerTickLimit=lowerTickLimit[[a]], lowerLabelLimit=lowerLabelLimit[[a]],
              upperTickLimit=upperTickLimit[[a]], upperLabelLimit=upperLabelLimit[[a]],
              line=line[[a]], forcedInterval=forcedInterval[[a]], ticklabels=ticklabels[[a]],
              ticksOut=ticksOut[[a]], forcePrint=forcePrint[[a]], ...)
  }

  # Still draw the labels even if we're not drawing the axis
  if(! 1 %in% axes && !is.null(xlab))
    draw_axis_label(1, xlab, labline[[1]], cex[[1]], ...)

  if(! 2 %in% axes && !is.null(ylab))
    draw_axis_label(2, ylab, labline[[2]], cex[[2]], ...)

}

#' Calculate a scale factor to transform between vectors
#'
#' @param y1,y2 Numeric vectors
#' @return c(scale,offset) to transform y2 into the same range as y1
#' @export
rescale <- function(y1,y2) {
  ylim=range(y1)
  y2lim=range(y2)
  scale=(ylim[[2]]-ylim[[1]])/(y2lim[[2]]-y2lim[[1]])
  offset=ylim[[1]]-y2lim[[1]]*scale
  return(c(scale=scale,offset=offset))
}

#Prepare environment to store scale settings for y2 axis
plot_options=new.env()

#' Rescales values onto the y2 axis
#'
#' @export
rescaleOntoY2 <- function(y) {
  y * plot_options$y2scale[[1]] + plot_options$y2scale[[2]]
}
