#' Calculates a tick inteval to make pretty plots
#' @param range The axis range
#' @param frac Allow fractional intervals?
#' @export
tick_interval <- function(range,frac=FALSE) {
  if(length(range) != 1) stop("'range' must be of length 1")
  nice=c(1,2,5,10)
  ti=10^floor(log10(range)) * nice[[which(range <= 10^floor(log10(range)) * nice)[[1]]]]/10
  if(!frac) {
    ti=ceiling(ti)
  }
  ti
}

#' Calculates tick locations to make pretty plots
#' @param min,max The minimum / maximum axis limits
#' @param div Divide the calculated interval by this number (to generate minor ticks)
#' @param frac Allow fractional intervals?
#' @param flexible Allow min and max to be adjusted for prettier results?
#' @export
pretty_ticks <- function(min,max,frac=FALSE, div=1, flexible=TRUE) {
  tickInterval<-tick_interval(max-min)/div
  tickStart=signif(min,1)
  tickEnd=signif(max,1)
  #Range is only to 1 sf, so extend it to make sure we cover everything
  ticksat=seq(tickStart-tickInterval*10,tickEnd+tickInterval*10,tickInterval)
  if(flexible) {
    ticksat=round(ticksat/tickInterval)*tickInterval
  }
  ticksat
}


#' Draws a bounding box and pretty axes
#'
#' Draws a bounding box and axes with tick positions generated by \code{\link{pretty_ticks}}
#' @param min,max vector of minimum / maximum axis limits c(x, y)
#' @param div Factor by which the minor tick interval is smaller than the major tick interval c(x,y)
#' @param x_axis,y_axis Side on which to draw the x,y axes
#' @param ... Additional parameters are passed to the underlying function calls
#' @inheritParams pretty_ticks
#' @export
pretty_axes <- function(min, max, x_axis=1, y_axis=2, frac=FALSE,div=1,flexible=TRUE,...) {
  #Draw the bounding box
  box()

  draw_axis <- function(min,max, axisSide, frac,div,flexible,...) {
    #Add some axes
    ticksat=pretty_ticks(min,max,frac,div,flexible)
    Minorticksat=pretty_ticks(min,max,frac,div,flexible)
    Minorticksat=Minorticksat[!(Minorticksat %in% ticksat)]

    #Add minor ticks
    axis(side = axisSide, tcl = -.2, at=Minorticksat, labels = NA,...)
    #Add major ticks
    axis(side = axisSide, tcl = -.4, at=ticksat, labels = NA,...)
    #Add labels (With reduced spacing from axis -- line=.4)
    axis(side = axisSide, lwd = 0,tcl = -0.5, line = -.6, at=ticksat,...)
  }

  if(length(min)==1) min=c(min,min)
  if(length(max)==1) max=c(max,max)
  if(length(div)==1) div=c(div,div)
  if(!is.na(x_axis)) {
    draw_axis(min[[1]],max[[1]],x_axis,frac,div[[1]],flexible,...)
  }
  if(!is.na(y_axis)) {
    draw_axis(min[[2]],max[[2]],y_axis,frac,div[[2]],flexible,...)
  }
}
